namespace: devops-portfolio

appName: frontend-main

replicas: 1

image: 026978711726.dkr.ecr.eu-central-1.amazonaws.com/devops-portfolio:main-43a8b4b719e1798ae20ffea2dabb853b9e8fad68

imagePullSecrets: regcred
